var searchData=
[
  ['serviceresource',['ServiceResource',['../class_twilio_1_1_rest_1_1_chat_1_1_v1_1_1_service_resource.html',1,'Twilio.Rest.Chat.V1.ServiceResource'],['../class_twilio_1_1_rest_1_1_chat_1_1_v2_1_1_service_resource.html',1,'Twilio.Rest.Chat.V2.ServiceResource'],['../class_twilio_1_1_rest_1_1_ip_messaging_1_1_v1_1_1_service_resource.html',1,'Twilio.Rest.IpMessaging.V1.ServiceResource'],['../class_twilio_1_1_rest_1_1_ip_messaging_1_1_v2_1_1_service_resource.html',1,'Twilio.Rest.IpMessaging.V2.ServiceResource']]],
  ['shortcoderesource',['ShortCodeResource',['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_short_code_resource.html',1,'Twilio::Rest::Api::V2010::Account']]],
  ['signingkeyresource',['SigningKeyResource',['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_signing_key_resource.html',1,'Twilio::Rest::Api::V2010::Account']]],
  ['sourceenum',['SourceEnum',['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_recording_resource_1_1_source_enum.html',1,'Twilio::Rest::Api::V2010::Account::RecordingResource']]],
  ['statusenum',['StatusEnum',['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_call_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.CallResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_conference_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.ConferenceResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.AccountResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_transcription_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.TranscriptionResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_recording_1_1_add_on_result_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.Recording.AddOnResultResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_conference_1_1_participant_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.Conference.ParticipantResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_taskrouter_1_1_v1_1_1_workspace_1_1_task_resource_1_1_status_enum.html',1,'Twilio.Rest.Taskrouter.V1.Workspace.TaskResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_call_1_1_feedback_summary_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.Call.FeedbackSummaryResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_recording_1_1_transcription_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.Recording.TranscriptionResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_taskrouter_1_1_v1_1_1_workspace_1_1_task_1_1_reservation_resource_1_1_status_enum.html',1,'Twilio.Rest.Taskrouter.V1.Workspace.Task.ReservationResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_taskrouter_1_1_v1_1_1_workspace_1_1_worker_1_1_reservation_resource_1_1_status_enum.html',1,'Twilio.Rest.Taskrouter.V1.Workspace.Worker.ReservationResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_message_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.MessageResource.StatusEnum'],['../class_twilio_1_1_rest_1_1_api_1_1_v2010_1_1_account_1_1_recording_resource_1_1_status_enum.html',1,'Twilio.Rest.Api.V2010.Account.RecordingResource.StatusEnum']]],
  ['stringenum',['StringEnum',['../class_twilio_1_1_types_1_1_string_enum.html',1,'Twilio::Types']]],
  ['stringenumconverter',['StringEnumConverter',['../class_twilio_1_1_converters_1_1_string_enum_converter.html',1,'Twilio::Converters']]],
  ['syncgrant',['SyncGrant',['../class_twilio_1_1_jwt_1_1_access_token_1_1_sync_grant.html',1,'Twilio::Jwt::AccessToken']]],
  ['systemnethttpclient',['SystemNetHttpClient',['../class_twilio_1_1_http_1_1_system_net_http_client.html',1,'Twilio::Http']]]
];
